/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API discovery */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API metadata and available endpoints */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            upstream?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}/reliability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compute reliability index
         * @description Computes and returns the reliability index for a user based on their
         *     transaction history within a 6-month scoring window.
         *
         *     The scoring window extends 6 calendar months back from the `from` date.
         *     Example: `from=2026-02-20` → window is `2025-09-01` to `2026-02-20`.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description End date of the scoring window (YYYY-MM-DD). The window extends 6 months back.
                     * @example 2026-02-20
                     */
                    from: string;
                };
                header?: never;
                path: {
                    /** @example user_1001 */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reliability score with metrics and explanatory drivers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "user_id": "user_1001",
                         *       "from": "2026-02-20",
                         *       "currency": "EUR",
                         *       "reliability_index": 64,
                         *       "score_band": "MEDIUM",
                         *       "metrics": {
                         *         "income_regularity": 0.83,
                         *         "income_coverage_ratio": 1.41,
                         *         "essential_payments_consistency": 0.89,
                         *         "good_months": 4,
                         *         "negative_balance_days": 54,
                         *         "late_fee_events": 1
                         *       },
                         *       "drivers": [
                         *         "Income present in 5/6 months",
                         *         "Income covers essential expenses (1.41x)",
                         *         "Essential payments detected consistently",
                         *         "Savings behavior detected (+13 pts)",
                         *         "Estimated 54 negative balance day(s) (-10 pts)",
                         *         "1 late fee event(s) detected (-1 pts)",
                         *         "Good cashflow months: 4/6"
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["ReliabilityResponse"];
                    };
                };
                /** @description Missing `from` parameter */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user transactions
         * @description Returns transactions for a user within a date range.
         *
         *     Supports two pagination modes:
         *     - **Cursor-based**: Use `cursor` parameter from previous response's `next_cursor`
         *     - **Offset/limit**: Use `page` and `limit` parameters
         *
         *     **Note:** If no pagination parameters are provided, ALL transactions are returned.
         *     For large date ranges this can be 10,000+ records.
         *
         *     Transactions are returned in arbitrary order. Client-side sorting is required.
         *
         *     No category filtering is available. All categories are included in the response.
         */
        get: {
            parameters: {
                query: {
                    /** @example 2025-09-01 */
                    from: string;
                    /** @example 2026-02-20 */
                    to: string;
                    /** @description Cursor for cursor-based pagination */
                    cursor?: string;
                    /** @description Page number (1-indexed) for offset pagination */
                    page?: number;
                    /** @description Number of items per page (default 50 when using pagination) */
                    limit?: number;
                };
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Transaction list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CursorPaginatedResponse"] | components["schemas"]["OffsetPaginatedResponse"] | components["schemas"]["UnpaginatedResponse"];
                    };
                };
                /** @description Missing required parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}/transaction-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Transaction update stream (SSE)
         * @description Server-Sent Events stream that delivers real-time transaction updates.
         *
         *     The stream sends a pre-scripted sequence of events over ~30 seconds,
         *     then closes. Events include:
         *     - `TRANSACTION_ADDED` — New transaction created
         *     - `TRANSACTION_UPDATED` — Existing transaction modified
         *     - `TRANSACTION_DELETED` — Transaction removed
         *
         *     Each event has an `id` field for reconnection support.
         *
         *     **Note:** `Last-Event-ID` header is accepted but not used for replay.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE event stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ReliabilityResponse: {
            user_id?: string;
            /** Format: date */
            from?: string;
            currency?: string;
            reliability_index?: number;
            /** @enum {string} */
            score_band?: "LOW" | "MEDIUM" | "HIGH";
            metrics?: components["schemas"]["ScoringMetrics"];
            /** @description Human-readable explanations of scoring factors */
            drivers?: string[];
        };
        ScoringMetrics: {
            /** @description Ratio: months_with_income / 6 */
            income_regularity?: number;
            /** @description Ratio: total_income / total_essential_expenses */
            income_coverage_ratio?: number;
            /** @description Ratio: present category-months / expected category-months */
            essential_payments_consistency?: number;
            /** @description Months where income exceeded essential expenses */
            good_months?: number;
            /** @description Estimated days with negative running balance */
            negative_balance_days?: number;
            /** @description Number of late fee transactions detected */
            late_fee_events?: number;
        };
        Transaction: {
            id?: string;
            account_id?: string;
            user_id?: string;
            /** @description Negative = debit, positive = credit */
            amount?: number;
            currency?: string;
            /** Format: date */
            date?: string;
            description?: string;
            merchant_category_code?: string;
            merchant_name?: string;
            /**
             * @description Redundant with amount sign (deliberate)
             * @enum {string}
             */
            type?: "debit" | "credit";
            /** Format: date-time */
            synced_at?: string;
        };
        CursorPaginatedResponse: {
            transactions?: components["schemas"]["Transaction"][];
            next_cursor?: string | null;
            total?: number;
        };
        OffsetPaginatedResponse: {
            transactions?: components["schemas"]["Transaction"][];
            total?: number;
            page?: number;
            limit?: number;
            total_pages?: number;
            has_more?: boolean;
        };
        UnpaginatedResponse: {
            transactions?: components["schemas"]["Transaction"][];
            total?: number;
            has_more?: boolean;
        };
        TransactionEvent: {
            /** @enum {string} */
            type?: "TRANSACTION_ADDED" | "TRANSACTION_UPDATED" | "TRANSACTION_DELETED";
            transaction?: components["schemas"]["Transaction"];
            /** @description Only present for TRANSACTION_DELETED events */
            transaction_id?: string;
        };
        Error: {
            error?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
